test:
	cargo test
test-noconcurrent:
	cargo test -- --test-threads=1
testv:
	cargo test -- --nocapture
testone:
	cargo test it_works
testignored:
	cargo test -- --ignored
testonefile:
	cargo test --test integration_test